name: Trigger PRs to sync branches

on:
  pull_request:
    types: [closed]
    
jobs:

  promote-pr-internal:
    if: github.ref == 'dev' && github.event.pull_request.merged == true
    uses: ./.github/workflows/promote-branch.yaml
    with:
      DESTINATION_BRANCH: qa
    secrets: inherit

  promote-pr-qa:
    if: github.ref == 'qa' && github.event.pull_request.merged == true
    uses: ./.github/workflows/promote-branch.yaml
    with:
      DESTINATION_BRANCH: main
    secrets: inherit

  merge-main-back-to-internal:
    if: github.ref == 'main' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: main
          destination_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore(auto-sync): main to internal'
          pr_body: ':crown: *An automated PR to sync from main to internal branch*'
          pr_label: automerge
          pr_reviewer: ${{ env.sync_reviewers }}
          pr_allow_empty: true