name: Trigger PRs to sync branches

on:
  pull_request:
    types: [closed]
    
jobs:
  promote-pr-internal:
    if: github.ref == 'dev' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Promote ${{ github.head_ref }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{github.head_ref}}
          destination_branch: qa
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "chore(auto-promote): ${{github.head_ref}} to qa"
          pr_body: ":arrow_up: *An automated PR to promote from ${{github.head_ref}} to qa branch*"
          pr_label: autopromote
  
  promote-pr-qa:
    if: github.ref == 'qa' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          source_branch: ${{github.head_ref}}
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "chore(auto-promote): ${{github.head_ref}} to main"
          pr_body: ":arrow_up: *An automated PR to promote from ${{github.head_ref}} to main branch*"
          pr_label: autopromote
        
  sync-pr-main:
    if: github.ref == 'main' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Promote ${{ github.head_ref }}
          uses: repo-sync/pull-request@v2
          with:
            source_branch: ${{github.head_ref}}
            destination_branch: dev
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_title: "chore(auto-sync): ${{github.head_ref}} to dev"
            pr_body: ":arrow_up: *An automated PR to sync from ${{github.head_ref}} to dev branch*"
            pr_label: autopromote
        