name: Trigger PRs to sync branches

on:
  pull_request:
    types: [closed]
    
jobs:
  promote-pr-internal:
    if: github.ref == 'dev' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base qa --head dev --label "autopromote" --title "chore(promote): dev to qa" --body ":arrow_up: *An automated PR to promote dev to qa*"
  
  gpromote-pr-qa:
    if: github.ref == 'qa' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head qa --label "autopromote" --title "chore(promote): qa to main" --body ":arrow_up: *An automated PR to promote qa to main*"
        
  sync-pr-main:
    if: github.ref == 'main' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base dev --head main --label "sync" --title "chore(sync): main to dev" --body ":arrow_up: *An automated PR to sync main to dev*"
        