name: Generate Pull Request

on:
  pull_request:
    types: [closed]
    
jobs:
  promote-pr-internal:
    if: github.ref == 'dev' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Promote dev to qa
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: qa
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "chore(auto-promote): dev to qa"
          pr_body: ":arrow_up: *An automated PR to promote from dev to qa branch*"
          pr_label: autopromote
  
  promote-pr-qa:
    if: github.ref == 'qa' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Promote qa to prod
        uses: repo-sync/pull-request@v2
        with:
          source_branch: qa
          destination_branch: prod
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "chore(auto-promote): qa to prod"
          pr_body: ":arrow_up: *An automated PR to promote from qa to prod branch*"
          pr_label: autopromote
        
  sync-pr-prod:
    if: github.ref == 'prod' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Sync prod to dev
          uses: repo-sync/pull-request@v2
          with:
            source_branch: prod
            destination_branch: dev
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pr_title: "chore(auto-sync): prod to dev"
            pr_body: ":arrow_up: *An automated PR to sync from prod to dev branch*"
            pr_label: autopromote
        