name: Trigger PRs to sync branches

on:
  pull_request:
    types: [closed]
    
jobs:

  promote-pr-internal:
    if: github.ref == 'dev' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          gh pr create --base qa --head dev --label "autopromote" --title "chore(promote): dev to qa"


  # promote-pr-internal:
  #   if: github.ref == 'dev' && github.event.pull_request.merged == true
  #   timeout-minutes: 2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Promote ${{ github.head_ref }}
  #       uses: repo-sync/pull-request@v2
  #       with:
  #         source_branch: dev
  #         destination_branch: qa
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         pr_title: "chore(auto-promote): dev to qa"
  #         pr_body: ":arrow_up: *An automated PR to promote from dev to qa branch*"
  #         pr_label: autopromote

  promote-pr-qa:
    if: github.ref == 'qa' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Promote ${{ github.head_ref }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: qa
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "chore(auto-promote): qa to main"
          pr_body: ":arrow_up: *An automated PR to promote from qa to main branch*"
          pr_label: autopromote

  merge-main-back-to-internal:
    if: github.ref == 'main' && github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: main
          destination_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore(auto-sync): main to dev'
          pr_body: ':crown: *An automated PR to sync from main to dev branch*'
          pr_label: automerge
          pr_reviewer: ${{ env.sync_reviewers }}
          pr_allow_empty: true